version: '3.8'

services:
  db:
    container_name: ${DB_HOST}
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - .cache/.postgresql:/var/lib/postgresql
    networks:
      - app-net
  server:
    container_name: nestjs-boilerplate
    build:
      dockerfile: ./ci/Dockerfile.dev
    ports:
      - "${PORT}:${PORT}"
      - "${DEBUG_PORT}:${DEBUG_PORT}"
    volumes:
      - ./:/server
    env_file:
      - ./.env
    depends_on:
      - db
    command: pnpm entrypoint
    networks:
      - app-net

networks:
  app-net:
    external: true