name: Auto version update
on:
  push:
    branches:
      - main
    tags: []
    
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: git global config
        run: |
          git config --global user.email "bonoself@gmail.com"
          git config --global user.name "bino"
      - name: patch version
        run: |
            npm version patch --git-tag-version false

      - name: read package.json
        id: info
        uses: jaywcjlove/github-action-package@main

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_author: release[bot] <actions@github.com>
          commit_message: 'release ${{ steps.info.outputs.version }}' 
          tagging_message: '${{ steps.info.outputs.version }}'
          push_options: '--tag'