name: Auto version update
on:
  push:
    tags:
      - '!*'
    # branches:
    #   - main
    
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Check Tag
        run: |
          if [[ -z ${{ github.ref }} ]]; then
            echo 'tag not exist'
          else
            echo 'tag exist'
          exit 0
          fi

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: git global config
        run: |
          git config --global user.email "bonoself@gmail.com"
          git config --global user.name "bino"
      - name: patch version
        run: |
            npm version patch --git-tag-version false

      - name: read package.json
        id: info
        uses: jaywcjlove/github-action-package@main

      - uses: EndBug/add-and-commit@v9 # You can change this to use a specific version.
        with:
          author_name: release[bot]
          author_email: actions@github.com
          message: 'tag: ${{ steps.info.outputs.version }}'
          push: true
          tag: '${{ steps.info.outputs.version }}'

          
      # - name: Changelog CI
      #   uses: saadmk11/changelog-ci@v1.1.2
      #   with:
      #     committer_username: 'release[bot]'
      #     committer_email: 'actions@github.com'
      #     release_version: ${{ steps.info.outputs.version }}
      #     changelog_filename: CHANGELOG.rst
      #     config_file: changelog.config.json
      # - name: Get Changelog Output
      #   run: |
      #     echo "${{ steps.changelog-ci.outputs.changelog }}"
      #     echo "${{ steps.changelog-ci.outputs.changelog }}" >> $GITHUB_STEP_SUMMARY